pipeline {
    agent any

    environment {
        APP_NAME = 'OnlineExamEvaluationSystem'
        APP_VERSION = '1.0.0'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/PDGamerSG/Assessment-7-Question-1/tree/master/Project3_Custom_Environment_Variables'
            }
        }

        stage('Show App Info') {
            steps {
                echo "Building ${env.APP_NAME}, version ${env.APP_VERSION}"
            }
        }

        stage('Build') {
            steps {
                dir('Project3_Custom_Environment_Variables') {
                    bat 'python -m py_compile app.py'
                    echo "${env.APP_NAME} version ${env.APP_VERSION} compiled successfully."
                }
            }
        }
    }
}
