pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/PDGamerSG/Assessment-7-Question-1.git'
            }
        }

        stage('Generate Report') {
            steps {
                dir('Project2_Archive_Artifacts') {
                    bat '"C:\\Users\\Administrator\\Local\\Programs\\Python\\Python313\\python.exe" app.py'
                }
            }
        }

        stage('Archive Report') {
            steps {
                dir('Project2_Archive_Artifacts') {
                    archiveArtifacts artifacts: 'report.txt', fingerprint: true
                }
            }
        }
    }
}
