pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/PDGamerSG/Assessment-7-Question-1/tree/master/Project2_Archive_Artifacts'
            }
        }

        stage('Generate Report') {
            steps {
                dir('Project2_Archive_Artifacts') {
                    bat 'python app.py'
                }
            }
        }

        stage('Archive Report') {
            steps {
                dir('Project2_Archive_Artifacts') {
                    archiveArtifacts artifacts: 'report.txt', fingerprint: true
                }
            }
        }
    }
}
