pipeline {
    agent any

    parameters {
        choice(name: 'EXAM_TYPE', choices: ['quiz', 'midterm', 'final'], description: 'Select the exam type to build for')
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/PDGamerSG/Assessment-7-Question-1/tree/master/Project1_Parameterized_Build'
            }
        }

        stage('Show Parameter') {
            steps {
                echo "Selected exam type: ${params.EXAM_TYPE}"
            }
        }

        stage('Build for Exam Type') {
            steps {
                echo "Building the Online Examination and Evaluation System for the ${params.EXAM_TYPE} exam..."
            }
        }
    }
}
